# Generated by Django 5.2.3 on 2025-06-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetails',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=50, unique=True)),
                ('eventDescription', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
                ('eventVenue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='memmbershipDetails',
            fields=[
                ('membershipCategory', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=20)),
                ('membershipId', models.AutoField(primary_key=True, serialize=False)),
                ('validaty', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='eventRegistrationDetails',
            fields=[
                ('registrationId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.eventdetails')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.userdetails')),
            ],
        ),
    ]
